# fly.toml app configuration file
app = 'vesperlabs'
primary_region = 'mad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[env]
  ASSETS_URL = 'https://aether.onrender.com/assets'
  DEBUG = 'false'
  GIT_BRANCH = 'main'
  GIT_REPO = 'git@github.com:VesperLabs/aether.git'
  NODE_ENV = 'production'
  PEER_CLIENT_PORT = '443'
  PEER_SERVER_PORT = '9000'
  PORT = '8000'
  PUBLIC_DIR = '../public'
  SERVER_FPS = '20'
  SERVER_URL = 'https://vesperlabs.fly.dev'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1