# fly.toml app configuration file generated for vesperlabs on 2024-05-05T15:18:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vesperlabs'
primary_region = 'mad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  ASSETS_URL = 'https://aether.onrender.com/assets'
  DEBUG = 'false'
  GIT_BRANCH = 'main'
  GIT_REPO = 'git@github.com:VesperLabs/aether.git'
  NODE_ENV = 'production'
  PEER_CLIENT_PORT = '443'
  PEER_SERVER_PORT = '9000'
  PORT = '8080'
  PUBLIC_DIR = '../public'
  SERVER_FPS = '20'
  SERVER_URL = 'https://vesperlabs.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  processes = ['app']
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


[[http_service.checks]]
  grace_period = "30s"  
  interval = "15s"   
  method = "get"   
  path = "/health"   
  timeout = "2s"   


[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1